name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Run tests
        run: sbt test

      - name: Upload test results to BuildPulse for flaky test detection
        if: "!cancelled()" # Run this step even when the tests fail. Skip if the workflow is cancelled.
        uses: Workshop64/buildpulse-action@main
        with:
          account: 68192324 # Replace this value with your BuildPulse account ID
          repository: 460987190 # Replace this value with your BuildPulse repository ID
          path: target/test-reports
          key: ${{ secrets.BUILDPULSE_ACCESS_KEY_ID }}
          secret: ${{ secrets.BUILDPULSE_SECRET_ACCESS_KEY }}
